version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3.11.7-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: bitnami/mongodb:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_USERNAME: stock_market
      MONGODB_PASSWORD: stock_market
      MONGODB_ROOT_USER: admin
      MONGODB_ROOT_PASSWORD: admin
      MONGODB_DATABASE: stock_market

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://stock_market:stock_market@mongo:27017/stock_market
    depends_on:
      - mongo